---

is_debug: true
listen:
  type: port
  port: 8000
storage:
  host: localhost
  port: 5432
  name: block
  user: muqiyat
  password: muqiyat
token:
  key: mYq3t6w9z$C&F)J@
  telegram: 5631882858:AAGcSNjBbmcwkj_z1kqR6h3AkhOwa0j41OY
smtp:
  server:
  port: 465
  mail:
  password: 
