// Code generated by protoc-gen-go. DO NOT EDIT.
// source: face.proto

package face

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ComparisonRequest struct {
	// Types that are valid to be assigned to ComparisonOneof:
	//	*ComparisonRequest_OriginalMetadata
	//	*ComparisonRequest_OriginalImage
	//	*ComparisonRequest_ForCheck
	//	*ComparisonRequest_ForCheckImage
	ComparisonOneof      isComparisonRequest_ComparisonOneof `protobuf_oneof:"Comparison_oneof"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ComparisonRequest) Reset()         { *m = ComparisonRequest{} }
func (m *ComparisonRequest) String() string { return proto.CompactTextString(m) }
func (*ComparisonRequest) ProtoMessage()    {}
func (*ComparisonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{0}
}

func (m *ComparisonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComparisonRequest.Unmarshal(m, b)
}
func (m *ComparisonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComparisonRequest.Marshal(b, m, deterministic)
}
func (m *ComparisonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComparisonRequest.Merge(m, src)
}
func (m *ComparisonRequest) XXX_Size() int {
	return xxx_messageInfo_ComparisonRequest.Size(m)
}
func (m *ComparisonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComparisonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComparisonRequest proto.InternalMessageInfo

type isComparisonRequest_ComparisonOneof interface {
	isComparisonRequest_ComparisonOneof()
}

type ComparisonRequest_OriginalMetadata struct {
	OriginalMetadata *Metadata `protobuf:"bytes,1,opt,name=originalMetadata,proto3,oneof"`
}

type ComparisonRequest_OriginalImage struct {
	OriginalImage []byte `protobuf:"bytes,2,opt,name=originalImage,proto3,oneof"`
}

type ComparisonRequest_ForCheck struct {
	ForCheck *Metadata `protobuf:"bytes,3,opt,name=forCheck,proto3,oneof"`
}

type ComparisonRequest_ForCheckImage struct {
	ForCheckImage []byte `protobuf:"bytes,4,opt,name=forCheckImage,proto3,oneof"`
}

func (*ComparisonRequest_OriginalMetadata) isComparisonRequest_ComparisonOneof() {}

func (*ComparisonRequest_OriginalImage) isComparisonRequest_ComparisonOneof() {}

func (*ComparisonRequest_ForCheck) isComparisonRequest_ComparisonOneof() {}

func (*ComparisonRequest_ForCheckImage) isComparisonRequest_ComparisonOneof() {}

func (m *ComparisonRequest) GetComparisonOneof() isComparisonRequest_ComparisonOneof {
	if m != nil {
		return m.ComparisonOneof
	}
	return nil
}

func (m *ComparisonRequest) GetOriginalMetadata() *Metadata {
	if x, ok := m.GetComparisonOneof().(*ComparisonRequest_OriginalMetadata); ok {
		return x.OriginalMetadata
	}
	return nil
}

func (m *ComparisonRequest) GetOriginalImage() []byte {
	if x, ok := m.GetComparisonOneof().(*ComparisonRequest_OriginalImage); ok {
		return x.OriginalImage
	}
	return nil
}

func (m *ComparisonRequest) GetForCheck() *Metadata {
	if x, ok := m.GetComparisonOneof().(*ComparisonRequest_ForCheck); ok {
		return x.ForCheck
	}
	return nil
}

func (m *ComparisonRequest) GetForCheckImage() []byte {
	if x, ok := m.GetComparisonOneof().(*ComparisonRequest_ForCheckImage); ok {
		return x.ForCheckImage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ComparisonRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ComparisonRequest_OriginalMetadata)(nil),
		(*ComparisonRequest_OriginalImage)(nil),
		(*ComparisonRequest_ForCheck)(nil),
		(*ComparisonRequest_ForCheckImage)(nil),
	}
}

type ComparisonRespons struct {
	Coincidences         bool     `protobuf:"varint,1,opt,name=coincidences,proto3" json:"coincidences,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComparisonRespons) Reset()         { *m = ComparisonRespons{} }
func (m *ComparisonRespons) String() string { return proto.CompactTextString(m) }
func (*ComparisonRespons) ProtoMessage()    {}
func (*ComparisonRespons) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{1}
}

func (m *ComparisonRespons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComparisonRespons.Unmarshal(m, b)
}
func (m *ComparisonRespons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComparisonRespons.Marshal(b, m, deterministic)
}
func (m *ComparisonRespons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComparisonRespons.Merge(m, src)
}
func (m *ComparisonRespons) XXX_Size() int {
	return xxx_messageInfo_ComparisonRespons.Size(m)
}
func (m *ComparisonRespons) XXX_DiscardUnknown() {
	xxx_messageInfo_ComparisonRespons.DiscardUnknown(m)
}

var xxx_messageInfo_ComparisonRespons proto.InternalMessageInfo

func (m *ComparisonRespons) GetCoincidences() bool {
	if m != nil {
		return m.Coincidences
	}
	return false
}

type FindRequest struct {
	// Types that are valid to be assigned to FindOneof:
	//	*FindRequest_Metadata
	//	*FindRequest_Image
	FindOneof            isFindRequest_FindOneof `protobuf_oneof:"Find_oneof"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{2}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

type isFindRequest_FindOneof interface {
	isFindRequest_FindOneof()
}

type FindRequest_Metadata struct {
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type FindRequest_Image struct {
	Image []byte `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*FindRequest_Metadata) isFindRequest_FindOneof() {}

func (*FindRequest_Image) isFindRequest_FindOneof() {}

func (m *FindRequest) GetFindOneof() isFindRequest_FindOneof {
	if m != nil {
		return m.FindOneof
	}
	return nil
}

func (m *FindRequest) GetMetadata() *Metadata {
	if x, ok := m.GetFindOneof().(*FindRequest_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (m *FindRequest) GetImage() []byte {
	if x, ok := m.GetFindOneof().(*FindRequest_Image); ok {
		return x.Image
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FindRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FindRequest_Metadata)(nil),
		(*FindRequest_Image)(nil),
	}
}

type FindRespons struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRespons) Reset()         { *m = FindRespons{} }
func (m *FindRespons) String() string { return proto.CompactTextString(m) }
func (*FindRespons) ProtoMessage()    {}
func (*FindRespons) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{3}
}

func (m *FindRespons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRespons.Unmarshal(m, b)
}
func (m *FindRespons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRespons.Marshal(b, m, deterministic)
}
func (m *FindRespons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRespons.Merge(m, src)
}
func (m *FindRespons) XXX_Size() int {
	return xxx_messageInfo_FindRespons.Size(m)
}
func (m *FindRespons) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRespons.DiscardUnknown(m)
}

var xxx_messageInfo_FindRespons proto.InternalMessageInfo

func (m *FindRespons) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Metadata struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Extension            string   `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{4}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Metadata) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func init() {
	proto.RegisterType((*ComparisonRequest)(nil), "ComparisonRequest")
	proto.RegisterType((*ComparisonRespons)(nil), "ComparisonRespons")
	proto.RegisterType((*FindRequest)(nil), "FindRequest")
	proto.RegisterType((*FindRespons)(nil), "FindRespons")
	proto.RegisterType((*Metadata)(nil), "Metadata")
}

func init() {
	proto.RegisterFile("face.proto", fileDescriptor_543a5193e84d47c5)
}

var fileDescriptor_543a5193e84d47c5 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0xb4, 0x95, 0x64, 0x1a, 0xa1, 0x0e, 0x22, 0xa5, 0x78, 0x28, 0x51, 0x6c, 0x4f, 0x39,
	0x54, 0xb0, 0xf7, 0x56, 0x4a, 0x3d, 0x78, 0xd9, 0xb3, 0x20, 0x6b, 0x32, 0xa9, 0x8b, 0xcd, 0x4e,
	0x4d, 0x56, 0xf0, 0x57, 0xfd, 0x1b, 0x69, 0xd2, 0x4d, 0x5d, 0x02, 0xde, 0xf6, 0xbd, 0x19, 0xde,
	0xbe, 0xf7, 0x76, 0x01, 0x32, 0x99, 0x50, 0xbc, 0x2b, 0xd8, 0x70, 0xf4, 0xe3, 0xc1, 0xc5, 0x92,
	0xf3, 0x9d, 0x2c, 0x54, 0xc9, 0x5a, 0xd0, 0xe7, 0x17, 0x95, 0x06, 0xe7, 0x30, 0xe0, 0x42, 0x6d,
	0x94, 0x96, 0xdb, 0x67, 0x32, 0x32, 0x95, 0x46, 0x0e, 0xbd, 0xb1, 0x37, 0xed, 0xcf, 0x82, 0xd8,
	0x12, 0xeb, 0x8e, 0x68, 0x2d, 0xe1, 0x1d, 0x9c, 0x5b, 0xee, 0x29, 0x97, 0x1b, 0x1a, 0x9e, 0x8c,
	0xbd, 0x69, 0xb8, 0xee, 0x08, 0x97, 0xc6, 0x09, 0xf8, 0x19, 0x17, 0xcb, 0x77, 0x4a, 0x3e, 0x86,
	0xa7, 0x6d, 0xe1, 0x66, 0xb8, 0x17, 0xb4, 0xe7, 0x5a, 0xb0, 0x6b, 0x05, 0x1d, 0x7a, 0x81, 0x30,
	0x38, 0xc6, 0x78, 0x65, 0x4d, 0x9c, 0x45, 0x73, 0x37, 0x5a, 0xb9, 0x63, 0x5d, 0x62, 0x04, 0x61,
	0xc2, 0x4a, 0x27, 0x2a, 0x25, 0x9d, 0x50, 0x59, 0xc5, 0xf2, 0x85, 0xc3, 0x45, 0x2f, 0xd0, 0x5f,
	0x29, 0x9d, 0xda, 0x36, 0x26, 0xe0, 0xe7, 0xff, 0xb4, 0xd0, 0x0c, 0xf1, 0x0a, 0x7a, 0xca, 0x49,
	0x5d, 0xc3, 0x45, 0x08, 0xb0, 0xd7, 0x3b, 0xd8, 0xba, 0xb1, 0xea, 0xb5, 0xa1, 0x4b, 0xe8, 0x19,
	0x36, 0x72, 0x5b, 0x49, 0xf7, 0x44, 0x0d, 0xa2, 0x47, 0xf0, 0x9b, 0x52, 0x47, 0xe0, 0x67, 0x6a,
	0x4b, 0x5a, 0xe6, 0x54, 0x2d, 0x05, 0xa2, 0xc1, 0x78, 0x0d, 0x01, 0x7d, 0x1b, 0xd2, 0xa5, 0x62,
	0x5d, 0x5d, 0x1b, 0x88, 0x23, 0x31, 0x4b, 0xa1, 0xbb, 0x92, 0x09, 0xe1, 0x03, 0xc0, 0xb1, 0x09,
	0xc4, 0xb8, 0xf5, 0xe2, 0x23, 0x97, 0xab, 0x9c, 0x45, 0x1d, 0xbc, 0x85, 0xee, 0xde, 0x2a, 0x86,
	0xf1, 0x9f, 0x3e, 0x46, 0x16, 0x1d, 0xb6, 0xde, 0xce, 0xaa, 0xaf, 0x74, 0xff, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0xe3, 0x16, 0xa8, 0x22, 0x58, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FaceClient is the client API for Face service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FaceClient interface {
	Comparison(ctx context.Context, in *ComparisonRequest, opts ...grpc.CallOption) (*ComparisonRespons, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindRespons, error)
}

type faceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceClient(cc grpc.ClientConnInterface) FaceClient {
	return &faceClient{cc}
}

func (c *faceClient) Comparison(ctx context.Context, in *ComparisonRequest, opts ...grpc.CallOption) (*ComparisonRespons, error) {
	out := new(ComparisonRespons)
	err := c.cc.Invoke(ctx, "/Face/Comparison", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindRespons, error) {
	out := new(FindRespons)
	err := c.cc.Invoke(ctx, "/Face/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceServer is the server API for Face service.
type FaceServer interface {
	Comparison(context.Context, *ComparisonRequest) (*ComparisonRespons, error)
	Find(context.Context, *FindRequest) (*FindRespons, error)
}

// UnimplementedFaceServer can be embedded to have forward compatible implementations.
type UnimplementedFaceServer struct {
}

func (*UnimplementedFaceServer) Comparison(ctx context.Context, req *ComparisonRequest) (*ComparisonRespons, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Comparison not implemented")
}
func (*UnimplementedFaceServer) Find(ctx context.Context, req *FindRequest) (*FindRespons, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterFaceServer(s *grpc.Server, srv FaceServer) {
	s.RegisterService(&_Face_serviceDesc, srv)
}

func _Face_Comparison_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComparisonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).Comparison(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Face/Comparison",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).Comparison(ctx, req.(*ComparisonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Face/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Face_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Face",
	HandlerType: (*FaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Comparison",
			Handler:    _Face_Comparison_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _Face_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "face.proto",
}
