# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nface.proto\"\xa7\x01\n\x11\x43omparisonRequest\x12%\n\x10originalMetadata\x18\x01 \x01(\x0b\x32\t.MetadataH\x00\x12\x17\n\roriginalImage\x18\x02 \x01(\x0cH\x00\x12%\n\x10\x66orCheckMetadata\x18\x03 \x01(\x0b\x32\t.MetadataH\x00\x12\x17\n\rforCheckImage\x18\x04 \x01(\x0cH\x00\x42\x12\n\x10\x43omparison_oneof\")\n\x11\x43omparisonRespons\x12\x14\n\x0c\x63oincidences\x18\x01 \x01(\x08\"K\n\x0b\x46indRequest\x12\x1d\n\x08metadata\x18\x01 \x01(\x0b\x32\t.MetadataH\x00\x12\x0f\n\x05image\x18\x02 \x01(\x0cH\x00\x42\x0c\n\nFind_oneof\"/\n\x08Metadata\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\textension\x18\x02 \x01(\t\"\x1c\n\x0b\x46indRespons\x12\r\n\x05total\x18\x01 \x01(\x05\x32\x64\n\x04\x46\x61\x63\x65\x12\x36\n\nComparison\x12\x12.ComparisonRequest\x1a\x12.ComparisonRespons\"\x00\x12$\n\x04\x46ind\x12\x0c.FindRequest\x1a\x0c.FindRespons\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPARISONREQUEST._serialized_start=15
  _COMPARISONREQUEST._serialized_end=182
  _COMPARISONRESPONS._serialized_start=184
  _COMPARISONRESPONS._serialized_end=225
  _FINDREQUEST._serialized_start=227
  _FINDREQUEST._serialized_end=302
  _METADATA._serialized_start=304
  _METADATA._serialized_end=351
  _FINDRESPONS._serialized_start=353
  _FINDRESPONS._serialized_end=381
  _FACE._serialized_start=383
  _FACE._serialized_end=483
# @@protoc_insertion_point(module_scope)
