# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import face_pb2 as face__pb2


class FaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Comparison = channel.stream_unary(
                '/Face/Comparison',
                request_serializer=face__pb2.ComparisonRequest.SerializeToString,
                response_deserializer=face__pb2.ComparisonRespons.FromString,
                )
        self.Find = channel.stream_unary(
                '/Face/Find',
                request_serializer=face__pb2.FindRequest.SerializeToString,
                response_deserializer=face__pb2.FindRespons.FromString,
                )


class FaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Comparison(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Find(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Comparison': grpc.stream_unary_rpc_method_handler(
                    servicer.Comparison,
                    request_deserializer=face__pb2.ComparisonRequest.FromString,
                    response_serializer=face__pb2.ComparisonRespons.SerializeToString,
            ),
            'Find': grpc.stream_unary_rpc_method_handler(
                    servicer.Find,
                    request_deserializer=face__pb2.FindRequest.FromString,
                    response_serializer=face__pb2.FindRespons.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Face', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Face(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Comparison(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Face/Comparison',
            face__pb2.ComparisonRequest.SerializeToString,
            face__pb2.ComparisonRespons.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Find(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Face/Find',
            face__pb2.FindRequest.SerializeToString,
            face__pb2.FindRespons.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
